# Generated by Django 4.2.1 on 2023-06-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='check_unique_user_shopping_cart'),
        ),
    ]
