# Generated by Django 4.2.1 on 2023-06-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredients_amount'),
        ('favorites', '0004_alter_favorite_options_alter_favorite_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'in_shopping_cart', 'verbose_name': 'список покупок', 'verbose_name_plural': 'список покупок'},
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
